#cloud-config
preserve_hostname: False
hostname: fedora-metallb
fqdn: fedora-metallb.onp.example.local
packages:
  - zsh
  - git
  - pip
  - podman
  - make
  - lua
runcmd:
  - [ modprobe, ip_tables ]
  - [ modprobe, ip6_tables ]
  - [ su, onp, -c, "git clone https://github.com/kevydotvinu/dotfiles /home/onp/dotfiles" ]
  - [ su, onp, -c, "make -C /home/onp/dotfiles nvim" ]
  - [ su, onp, -c, "make -C /home/onp/dotfiles ohmyzsh" ]
  - [ su, onp, -c, "make -C /home/onp/dotfiles go-download GO_VERSION=go" ]
  - [ su, onp, -c, "make -C /home/onp/dotfiles kind-download" ]
  - [ su, onp, -c, "git clone https://github.com/kevydotvinu/metallb-metallb /home/onp/metallb-metallb" ]
  - [ su, onp, -c, "pip3 install invoke semver" ]
  - [ ln, -sfv, /usr/bin/podman, /usr/bin/docker ]
output:
  all: ">> /var/log/cloud-init.log"
users:
  - name: onp
    plain_text_passwd: 'Onp@123'
    lock-passwd: False
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
ssh_pwauth: True
